const tagList = [
	"Array",
	"Backtracking",
	"Binary Search",
	"Binary Search Tree",
	"Binary Tree",
	"Bit Manipulation",
	"Breadth-First Search",
	"Brute Force",
	"Counting",
	"Depth-First Search",
	"Disjoint Set Union",
	"Divide and Conquer",
	"Dynamic Programming",
	"Fenwick Tree",
	"Geometry",
	"Graph Theory",
	"Greedy",
	"Hash Table",
	"Heap / Priority Queue",
	"Implementation",
	"Linked List",
	"Math",
	"Matrix",
	"Minimum Spanning Tree",
	"Monotonic Queue",
	"Monotonic Stack",
	"Number Theory",
	"Prefix Sum",
	"Queue",
	"Recursion",
	"Searching",
	"Segment Tree",
	"Shortest Path",
	"Simulation",
	"Sliding Window",
	"Sorting",
	"Stack",
	"String",
	"Topological Sort",
	"Tree",
	"Trie",
	"Two Pointers"
];

export default tagList;
