const tagList = [
	"Arrays",
	"Strings",
	"Math",
	"Implementation",
	"Simulation",
	"Sorting",
	"Searching",
	"Binary Search",
	"Two Pointers",
	"Sliding Window",
	"Prefix Sum",
	"Hashing",
	"Bit Manipulation",
	"Recursion",
	"Backtracking",
	"Greedy",
	"Dynamic Programming",
	"Divide and Conquer",
	"Brute Force",
	"Trees",
	"Binary Trees",
	"Binary Search Trees",
	"Graphs",
	"DFS",
	"BFS",
	"Shortest Path",
	"Topological Sort",
	"Disjoint Set Union",
	"Minimum Spanning Tree",
	"Trie",
	"Heap / Priority Queue",
	"Stack",
	"Queue",
	"Linked List",
	"Segment Tree",
	"Fenwick Tree",
	"Monotonic Stack",
	"Monotonic Queue",
	"Geometry",
	"Combinatorics",
	"Number Theory",
	"Matrix"
];

export default tagList;
